:Author: ckuehnel
:Email: info@ckuehnel.ch
:Date: 06/05/2018
:Revision: version#
:License: GPL3.0

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

There is nothing to assemble

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 MKR1000:console_parsed            => Arduino sketch folder
  ├── MKR1000:console_parsed.ino   => main Arduino file
  ├── arduino_secrets.h            => Secrets   
  └── ReadMe.adoc                  => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ckuehnel <info@ckuehnel.ch>

=== BOM
You need no materials you need for this project.

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
